version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: scripts/start_misp
      runas: root
      timeout: 1200
  ValidateService:
    - location: scripts/after_misp_install
      timeout: 300
      runas: root


