version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/test
hooks:
  AfterInstall:
    - location: scripts/hostnameChange.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_misp
      runas: root
      timeout: 400


