version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/test
hooks:
  BeforeInstall:
    - location: scripts/hostnameChange.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_misp
      runas: root
      timeout: 1000
  ValidateService:
    - location: scripts/after_misp_install
      timeout: 300
      runas: root

